# 🎲 What is np.random?
✅ It is a submodule in NumPy used to generate random numbers of many types:
Integers

Floats

Random choices from arrays

Shuffling arrays

Normal (Gaussian) numbers

Uniform distributions

Many more!

In [3]:
# random.rand(): [0 1) uniform distribution

import numpy as np
arr = np.random.rand(2,3)
print(arr)

# random.randn(): random float values mean = 0 & std = 1 (standard normal distribution)

arr = np.random.randn(4,4)
print(arr)

# Random Integers
# np.random.randint(low, high, size)
# Generates random integers from low (inclusive) to high (exclusive).


arr = np.random.randint(0,10,size=(5,5))
print(arr)

[[0.82969975 0.76507504 0.49496428]
 [0.7341723  0.27624033 0.72609061]]
[[-0.04280932 -1.06924472 -0.23300755 -1.73719018]
 [-1.07842066 -0.66104074  0.32706114  1.05694392]
 [-0.95983449 -0.87864306  1.89825256 -0.22118896]
 [ 1.34131543 -1.39557385  0.3256621   2.18248698]]
[[6 1 0 3 5]
 [8 1 6 5 3]
 [8 6 5 2 6]
 [9 6 9 4 3]
 [1 9 9 6 9]]


In [12]:
# Random choice from an array

import numpy as np

arr = np.array([2,3,4,5,6,7,8,9])
print(np.random.choice(arr,size=(2,3))) # repetion may occur
print(np.random.choice(arr,size=(2,2),replace=False)) # repetion doesn't occur

[[7 5 4]
 [4 4 9]]
[[8 4]
 [3 2]]


In [ ]:
# shuffle : shuffles original

import numpy as np

arr = np.array([[2,3,4,5,6],[4,5,6,7,8]])

print(arr)
np.random.shuffle(arr)
print(arr)


# permutation: returns new array

newarr = np.random.permutation(arr)

print(arr) # original remains same
print(newarr)

[[2 3 4 5 6]
 [4 5 6 7 8]]
[[4 5 6 7 8]
 [2 3 4 5 6]]
[[4 5 6 7 8]
 [2 3 4 5 6]]
[[2 3 4 5 6]
 [4 5 6 7 8]]


In [ ]:
# seed: ensures reproducibility - same output for same seed

np.random.seed(1)

arr_one = np.random.randn(4)

# np.random.seed(2) # if u remove this comment only then output will change for second
arr_two = np.random.randn(4)

print(arr_one,arr_two)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862] [-0.41675785 -0.05626683 -2.1361961   1.64027081]
