In [1]:
import numpy as np

# 1. Creating arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a =", a)
print("b =", b)

# 2. Element-wise operations
print("\n--- Element-wise Operations ---")
print("a + b =", a + b)        # Addition
print("a - b =", a - b)        # Subtraction
print("a * b =", a * b)        # Multiplication
print("b / a =", b / a)        # Division
print("a ** 2 =", a ** 2)      # Square each element in a

# 3. Scalar operations
print("\n--- Scalar Operations ---")
print("a + 10 =", a + 10)
print("a * 2 =", a * 2)

# 4. 2D Arrays for Matrix vs Element-wise
print("\n--- 2D Array Operations ---")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A =\n", A)
print("B =\n", B)
print("Element-wise A * B =\n", A * B)
print("Matrix multiplication A @ B =\n", A @ B)  # or np.dot(A, B)

# 5. Math functions
print("\n--- Math Functions ---")
arr = np.array([1, 2, 3, 4, 5])
print("Array =", arr)
print("Sum =", np.sum(arr))
print("Mean =", np.mean(arr))
print("Min =", np.min(arr))
print("Max =", np.max(arr))
print("Std Dev =", np.std(arr))
print("Variance =", np.var(arr))

# 6. Axis-based operations
print("\n--- Axis Operations ---")
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Matrix m =\n", m)
print("Sum of rows (axis=1):", np.sum(m, axis=1))
print("Sum of columns (axis=0):", np.sum(m, axis=0))

# 7. Bonus Practice Set
print("\n--- Bonus Practice Set ---")
a = np.array([5, 10, 15])
b = np.array([2, 4, 6])
print("a =", a)
print("b =", b)
print("a + 3 =", a + 3)
print("a / b =", a / b)
print("a * b =", a * b)
print("Dot product of a and b =", np.dot(a, b))
print("Mean of b =", np.mean(b))


a = [1 2 3]
b = [4 5 6]

--- Element-wise Operations ---
a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
b / a = [4.  2.5 2. ]
a ** 2 = [1 4 9]

--- Scalar Operations ---
a + 10 = [11 12 13]
a * 2 = [2 4 6]

--- 2D Array Operations ---
A =
 [[1 2]
 [3 4]]
B =
 [[5 6]
 [7 8]]
Element-wise A * B =
 [[ 5 12]
 [21 32]]
Matrix multiplication A @ B =
 [[19 22]
 [43 50]]

--- Math Functions ---
Array = [1 2 3 4 5]
Sum = 15
Mean = 3.0
Min = 1
Max = 5
Std Dev = 1.4142135623730951
Variance = 2.0

--- Axis Operations ---
Matrix m =
 [[1 2 3]
 [4 5 6]]
Sum of rows (axis=1): [ 6 15]
Sum of columns (axis=0): [5 7 9]

--- Bonus Practice Set ---
a = [ 5 10 15]
b = [2 4 6]
a + 3 = [ 8 13 18]
a / b = [2.5 2.5 2.5]
a * b = [10 40 90]
Dot product of a and b = 140
Mean of b = 4.0
