In [1]:
import numpy as np

# Original 2x3 array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Original array:\n", a)

# Reshape to 3x2
reshaped = a.reshape(3, 2)
print("\nReshaped to 3x2:\n", reshaped)

# Reshape with -1
auto_shape = a.reshape(-1, 1)
print("\nReshape with -1 to column vector:\n", auto_shape)

# Flatten
flat = a.flatten()
print("\nFlattened array:", flat)

# Ravel (returns view)
ravelled = a.ravel()
print("Raveled array:", ravelled)

# Transpose
transposed = a.T
print("\nTransposed array:\n", transposed)


Original array:
 [[1 2 3]
 [4 5 6]]

Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Reshape with -1 to column vector:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Flattened array: [1 2 3 4 5 6]
Raveled array: [1 2 3 4 5 6]

Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
